### ISSUE TITLE
Not Healing

### ISSUE THREAD

**Issue by Miekell** [lorand-ffxi/HealBot#9] opened 2016-07-09 17:28 UTC
I apologize from the start because my knowledge is limited, I have sought additional help from people who know more but the end result being "It works perfectly except when it comes to healing."

**Comment by lorand-ffxi** [comment] 2016-07-19 22:40
When you say healing, do you mean resting, or curing?  Can you give an example situation where you were having issues?

**Comment by Miekell** [comment] 2016-07-19 23:50
Actually both. At Low MP it does not rest and at no point in time does it cure.

I have it loaded, I have it on, I have it set to watch my main and stay within curing range.

**Comment by lorand-ffxi** [comment] 2016-07-24 11:03
It isn't programmed to rest.  I haven't seen any issues with curing, but I will do some testing today.

**Comment by lorand-ffxi** [comment] 2016-07-24 12:47
I apologize, the issue is probably due to my not properly documenting the new dependency on https://github.com/lorand-ffxi/lor_libs

I have added additional information to the readme files to make it clearer.  Please let me know if that solves the issue that you were experiencing.

**Comment by lorand-ffxi** [comment] 2016-07-25 02:28
I believe this is fully fixed now!  When I had quit about a year ago, there was an error in the function to pick a cure tier that I didn't catch.  Additionally, if curaga wasn't disabled, then when a curaga was queued, it wouldn't allow single target cures to be queued.  

Now, curaga and single target cures share the same queue, though I give curaga a slightly higher weighted priority than single target cures.  Cure HP amounts are also now configurable via the cure_potency.xml settings file, as well as the minimum number of targets for curaga in the settings.xml file, under healing.  A new settings.xml will be generated with the default settings if you rename or delete your current one.

Please don't forget to download the new files in the link in my previous message as well, and to update them if you downloaded them earlier.  A message will be displayed in the future if you update HealBot and those files need to be updated as well.

I'll leave this issue open for now; please let me know if the changes I made resolved it.

**Comment by Miekell** [comment] 2016-07-26 23:03
I re-downloaded all needed files.
As soon as I am able to get it to load again I will let you know.

Last time I loaded it was a week ago before I did a fresh install of Win7

**Comment by lorand-ffxi** [comment] 2016-09-27 09:53
I encountered a situation where it would prioritize casting paralyna over casting cure... I'll work on tweaking the prioritization / logic behind choosing to cast a -na when cures are needed.

**Comment by lorand-ffxi** [comment] 2016-09-27 09:55
Additionally, I fixed an issue where it mis-classified targets compared to changes that appear to have been made in the resource files for valid targets of spells.  If this is what caused your issue, that should be fixed now.  If someone isn't in your party, you need to tell HB to monitor that player.

**Comment by lorand-ffxi** [comment] 2016-10-27 23:36
Closing because this is old now.  If you encounter an issue again, please open a new ticket.

**Closed by lorand-ffxi** 2016-10-27 23:36 UTC
Labels: bug
